version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-local
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=flow_mock_db
      - MYSQL_USER=flowuser
      - MYSQL_PASSWORD=flowpass
    volumes:
      - mysql_data:/var/lib/mysql

  redis-cache:
    image: redis:6.2-alpine
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: