apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-mock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flow-mock
  template:
    metadata:
      labels:
        app: flow-mock
    spec:
      containers:
        - name: flow-mock
          image: islene/flow-mock:0.1   # 用你的镜像
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flow-mock-service
spec:
  type: NodePort
  selector:
    app: flow-mock
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080   # 暴露到主机 30080 端口
